# Generated by Django 3.2.4 on 2021-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='datecompleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
